cpanm -n -f Catalyst::Runtime
cpanm -n -f Catalyst::Plugin::ConfigLoader
cpanm -n -f Catalyst::Plugin::Static::Simple
cpanm -n -f Catalyst::Action::RenderView
cpanm -n -f Catalyst::Model::MongoDB
cpanm -n -f Catalyst::Helper::Model::MongoDB
cpanm -n -f Catalyst::Plugin::Session::Store::MongoDB
cpanm -n -f Catalyst::Authentication::Store::MongoDB
cpanm -n -f Catalyst::Restarter
cpanm -n -f Catalyst::Plugin::Widget
cpanm -n -f Catalyst::Plugin::Cache::Store::FastMmap
cpanm -n -f Catalyst::Plugin::Cache::FastMmap
cpanm -n -f Catalyst::Plugin::I18N
cpanm -n -f Catalyst::Plugin::StatusMessage
cpanm -n -f Catalyst::Plugin::Session::State::Cookie
cpanm -n -f Catalyst::Plugin::Authentication
cpanm -n -f Catalyst::Plugin::StackTrace
cpanm -n -f Catalyst::Authentication::Credential::OpenID
cpanm -n -f Catalyst::Plugin::Authentication::Credential::OpenID
cpanm -n -f Plack::Middleware::RealIP
cpanm -n -f Plack::Middleware::SetEnvFromHeader
cpanm -n -f Plack::Middleware::SizeLimit
cpanm -n -f Plack::Middleware::XForwardedFor
cpanm -n -f HTTP::HeaderParser::XS
cpanm -n -f Net::Server::PreFork
cpanm -n -f Catalyst::Runtime
cpanm -n -f Catalyst::Engine::CGI
cpanm -n -f Catalyst::Engine::HTTP::Prefork
cpanm -n -f Catalyst::Plugin::Authorization::Roles
cpanm -n -f Text::Highlight
cpanm -n -f MooseX::NonMoose
cpanm -n -f DBIx::Class::TimeStamp
cpanm -n -f DBIx::Class::PassphraseColumn
cpanm -n -f JSON::XS
cpanm -n -f MongoDBx::Class
cpanm -n -f MongoDBx::Queue
cpanm -n -f Image::Magick
cpanm -n -f MooseX::DeepAccessors
cpanm -n -f MooseX::Traits::Pluggable
cpanm -n -f CatalystX::Component::Traits
cpanm -n -f DBIx::Class
cpanm -n -f DBIx::Class::Schema
cpanm -n -f CatalystX::Component::Traits
cpanm -n -f Catalyst::Model::DBIC::Schema
cpanm -n -f Catalyst::View::TT
cpanm -n -f Catalyst::View::JSON
cpanm -n -f Catalyst::View::CSV
cpanm -n -f Moose
cpanm -n -f namespace::autoclean
cpanm -n -f Config::General
cpanm -n -f Digest::SHA
cpanm -n -f Linux::Inotify2
cpanm -n -f YAML::XS
cpanm -n -f YAML::Syck
cpanm -n -f XML::Simple
cpanm -n -f WWW::Sitemap::XML
cpanm -n -f Any::Moose
#cpanm -n -f ZMQ::LibZMQ3 # export PERL_ZMQ_BACKEND='ZMQ::LibZMQ3'
#cpanm -n -f ZMQ::Constants
#cpanm -n -f ZMQ::ZMQ
#cpanm -n -f ZMQx::Class
#cpanm -n -f POEx::ZMQ3
cpanm -n -f Data::Localize::Storage::MongoDB
cpanm -n -f Log::Log4perl
cpanm -n -f Log::Log4perl::Catalyst
cpanm -n -f Template::Plugin::Class
cpanm -n -f Template::Plugin::AddTime
cpanm -n -f Template::Plugin::Body
cpanm -n -f Template::Plugin::Number::Format
cpanm -n -f Template::Plugin::Perl
cpanm -n -f Template::Plugin::RoundRobin
cpanm -n -f Template::Plugin::Shuffle
cpanm -n -f Template::Plugin::Subst
cpanm -n -f Template::Plugin::String::Truncate
cpanm -n -f Template::Plugin::Text::Filter::URI
cpanm -n -f Template::Plugin::Time::Duration
cpanm -n -f Template::Plugin::TimeDate
cpanm -n -f Template::Plugin::Timer
cpanm -n -f Template::Plugin::TruncateByWord
cpanm -n -f Template::Plugin::VMethods
cpanm -n -f Template::Plugin::Comma
cpanm -n -f Template::Plugin::DataPrinter
cpanm -n -f Template::Plugin::DateTime
cpanm -n -f Template::Plugin::DateTime::Format
cpanm -n -f Template::Plugin::Filter::Minify::CSS
cpanm -n -f Template::Plugin::Filter::Minify::CSS::XS
cpanm -n -f Template::Plugin::Filter::Minify::JavaScript
cpanm -n -f Template::Plugin::Filter::Minify::JavaScript::XS
cpanm -n -f Template::Plugin::Filter::MinifyHTML
cpanm -n -f Template::Plugin::Filter::String::Truncate
cpanm -n -f Template::Plugin::HighlightPerl
cpanm -n -f Template::Plugin::HtmlToText
cpanm -n -f Template::Plugin::JavaScript
cpanm -n -f Template::Plugin::LanguageName
cpanm -n -f Template::Plugin::ListOps
cpanm -n -f Template::Plugin::ListUtil
cpanm -n -f Template::Plugin::JSON
cpanm -n -f Template::Plugin::Cache
cpanm -n -f Template::Plugin::IO::All
cpanm -n -f Template::Plugin::Digest::MD5
cpanm -n -f App::cpanoutdated
cpanm -n -f Linux::Proc::Net::TCP
cpanm -n -f Daemon::Generic
cpanm -n -f Expect
cpanm -n -f Net::OpenSSH
cpanm -n -f FCGI
cpanm -n -f FCGI::ProcManager
cpanm -n -f Term::Size::Any
cpanm -n -f MIME::Types
cpanm -n -f IPC::System::Simple
cpanm -n -f IO::Interface
cpanm -n -f Catalyst::Plugin::SmartURI
cpanm -n -f Expect
cpanm -n -f Net::OpenSSH
cpanm -n -f Coro
cpanm -n -f subs::parallel
cpanm -n -f File::Slurp
cpanm -n -f Getopt::Long
cpanm -n -f Pod::Usage
cpanm -n -f AnyEvent::Timer::Cron
cpanm -n -f Proc::ProcessTable
cpanm -n -f URI::Encode
cpanm -n -f Catalyst::Model::Adaptor
cpanm -n -f Catalyst::Plugin::Authorization::ACL
cpanm -n -f Cache::Memcached::Fast
cpanm -n -f Test::More
cpanm -n -f URI::SmartURI
