#!/bin/bash

USER_NAME=$(cat ./etc/user)
PASSWORD=$(cat ./etc/password)
ROOT_PASSWORD=$(cat ./etc/root)

./deploy.pl \
    --plan make_config \
    --user $USER_NAME \
    --password $PASSWORD \
    --root_password $ROOT_PASSWORD \
    --timeout=1440 \
    --verbose \
    --host=config0.enslaver.net:220 \
    --host=config1.enslaver.net:220 \
    --host=config2.enslaver.net:220
