#!/bin/bash

USER_NAME=$(cat ./etc/suser)
PASSWORD=$(cat ./etc/password)
ROOT_PASSWORD=$(cat ./etc/root)

./deploy_bsd.pl \
    --plan restart_nginx \
    --user $USER_NAME \
    --password $PASSWORD \
    --root_password $ROOT_PASSWORD \
    --root \
    --timeout=1440 \
    --verbose \
    --host=node0.lambda-cloud.net:220 \
    --host=node1.lambda-cloud.net:220 \
    --host=node2.lambda-cloud.net:220 \
    --host=node3.lambda-cloud.net:220 \
    --host=node4.lambda-cloud.net:220 \
    --host=node5.lambda-cloud.net:220 \
    --host=node6.lambda-cloud.net:220 \
    --host=node7.lambda-cloud.net:220
