#!/bin/bash

USER_NAME=$(cat ./etc/user)
PASSWORD=$(cat ./etc/password)
ROOT_PASSWORD=$(cat ./etc/root)

./deploy.pl \
    --plan generate_fw_rules \
    --user $USER_NAME \
    --password $PASSWORD \
    --root_password $ROOT_PASSWORD \
    --timeout=1440 \
    --verbose \
    --host=node0.lambda-cloud.net:220 \
    --host=node1.lambda-cloud.net:220 \
    --host=node2.lambda-cloud.net:220 \
    --host=node3.lambda-cloud.net:220 \
    --host=node4.lambda-cloud.net:220 \
    --host=node5.lambda-cloud.net:220 \
    --host=node6.lambda-cloud.net:220 \
    --host=node7.lambda-cloud.net:220

./deploy.pl \
    --plan reload_fw_rules \
    --user $USER_NAME \
    --password $PASSWORD \
    --root_password $ROOT_PASSWORD \
    --root \
    --timeout=1440 \
    --verbose \
    --host=node0.lambda-cloud.net:220 \
    --host=node1.lambda-cloud.net:220 \
    --host=node2.lambda-cloud.net:220 \
    --host=node3.lambda-cloud.net:220 \
    --host=node4.lambda-cloud.net:220 \
    --host=node5.lambda-cloud.net:220 \
    --host=node6.lambda-cloud.net:220 \
    --host=node7.lambda-cloud.net:220

./deploy.pl \
    --plan reload_fw_rules_config \
    --user $USER_NAME \
    --password $PASSWORD \
    --root_password $ROOT_PASSWORD \
    --root \
    --timeout=1440 \
    --verbose \
    --host=config0.lambda-cloud.net:220 \
    --host=config1.lambda-cloud.net:220 \
    --host=config2.lambda-cloud.net:220
