#!/bin/bash

mongod --config /home/slayer/devel/perl/Slaver/etc/mongod_rset_b_1.conf
mongod --config /home/slayer/devel/perl/Slaver/etc/mongod_rset_b_2.conf
mongod --config /home/slayer/devel/perl/Slaver/etc/mongod_rset_b_3.conf

mongo localhost:10004/admin /home/slayer/devel/perl/Slaver/etc/init_rset_b.js
