#!/bin/bash

NGINX_USER=nginx
NGINX_GROUP=nginx

UPLOAD_ROOT=/home/developer/devel/perl/Slaver
UPLOAD_DIR=var/tmp

for i in {0..9} {a..z} {A..Z}
do
    mkdir -p "$UPLOAD_ROOT/$UPLOAD_DIR/upload_state/$i";
    mkdir -p "$UPLOAD_ROOT/$UPLOAD_DIR/upload_store/$i";
done

chown -R $NGINX_USER:$NGINX_GROUP "$UPLOAD_ROOT/$UPLOAD_DIR/upload_state"
chown -R $NGINX_USER:$NGINX_GROUP "$UPLOAD_ROOT/$UPLOAD_DIR/upload_store"
