#!/bin/bash

SERVICE_ROOT="/home/developer/devel/perl/Slaver/"

SERVICE_WORKERS="2"

SERVICE_ARGS="--daemonize"

SERVICE_IMAGE="starman"

SERVICE_USER="developer"
SERVICE_GROUP="developer"

SERVICE_APPLICATION="Slaver"
SERVICE_APPLICATION_IMAGE="slaver.psgi"

SERVICE_APPLICATION_CMD_PID=$(ps ax -opid,ppid,args | awk '{if ($3" "$4 == "starman master") print($1);}')

SERVICE_PID_FILE="${SERVICE_ROOT}var/run/slaver.pid"
SERVICE_LISTEN="127.0.0.1:8080"
SERVICE_SOCKET_FILE="${SERVICE_ROOT}var/run/slaver.sock"

if [ ! -f $SERVICE_PID_FILE ];
then
    echo -n "0" > $SERVICE_PID_FILE
fi

SERVICE_PID=$(<$SERVICE_PID_FILE)

if [ "$SERVICE_PID" != "0" ];
then
    echo Service pid $SERVICE_PID
fi

if [ "$SERVICE_APPLICATION_CMD_PID" != "" ];
then
    if [ "$SERVICE_APPLICATION_CMD_PID" != "$SERVICE_PID" ];
    then
	echo Service process $SERVICE_APPLICATION_CMD_PID exists, but not in the pid file
	SERVICE_PID=$SERVICE_APPLICATION_CMD_PID
    fi
fi

status() {
    echo Checking status $SERVICE_APPLICATION

    if [ "$SERVICE_PID" != "0" ];
    then
	echo Service is running
	exit 0
    else
	echo Service is stopped
	exit 1
    fi
}

start() {
    echo Starting $SERVICE_APPLICATION

    cd $SERVICE_ROOT
    $SERVICE_IMAGE --workers $SERVICE_WORKERS --listen $SERVICE_LISTEN --listen $SERVICE_SOCKET_FILE --pid $SERVICE_PID_FILE --user $SERVICE_USER --group $SERVICE_GROUP $SERVICE_ARGS $SERVICE_APPLICATION_IMAGE
}

stop() {
    echo Killing $SERVICE_APPLICATION

    if [ "$SERVICE_PID" == "0" ];
    then
	 echo "Service is already stoped"
    else
	kill -TERM $SERVICE_PID > /dev/null 2>&1
	sleep 1
    fi

    rm -f $SERVICE_PID_FILE
}

reload() {
    echo Restarting $SERVICE_APPLICATION

    if [ "$SERVICE_PID" == "0" ];
    then
	 echo "Service is already stoped"
    else
	kill -HUP $SERVICE_PID > /dev/null 2>&1
	sleep 1
    fi
}

case "$1" in
  start)
    stop
    sleep 1
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  reload)
    reload
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|reload|restart}"
esac

exit 0
